# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zs\Desktop\新项目\ui\ui2025.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1403, 876)
        MainWindow.setStyleSheet("QMainWindow{\n"
"\n"
"\n"
"background-color:;    /*背景颜色*/\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(71, 227, 871, 491))
        self.graphicsView.setStyleSheet("QGraphicsView{\n"
"\n"
"border:1px solid  black;   /*边框的粗细，颜色*/\n"
"\n"
"\n"
"\n"
"\n"
"}")
        self.graphicsView.setObjectName("graphicsView")
        self.label_headline = QtWidgets.QLabel(self.centralwidget)
        self.label_headline.setGeometry(QtCore.QRect(600, 10, 391, 31))
        self.label_headline.setStyleSheet("QLabel{\n"
"\n"
"\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 20pt \"隶书\";\n"
"\n"
"font: 30px;        /*设置按钮文字和大小*/\n"
"}")
        self.label_headline.setObjectName("label_headline")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(71, 117, 871, 108))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_vibration_analysis = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_vibration_analysis.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color: rgb(255, 231, 151);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 18pt \"楷体\";\n"
"min-width:100px;    /*设置最小宽度*/\n"
"min-height:80px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_vibration_analysis.setObjectName("pushButton_vibration_analysis")
        self.horizontalLayout_4.addWidget(self.pushButton_vibration_analysis)
        self.pushButton_otherpara = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_otherpara.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color: rgb(255, 231, 151);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 18pt \"楷体\";\n"
"min-width:100px;    /*设置最小宽度*/\n"
"min-height:80px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_otherpara.setObjectName("pushButton_otherpara")
        self.horizontalLayout_4.addWidget(self.pushButton_otherpara)
        self.pushButton_dataset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_dataset.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color: rgb(255, 231, 151);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 18pt \"楷体\";\n"
"min-width:100px;    /*设置最小宽度*/\n"
"min-height:80px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_dataset.setObjectName("pushButton_dataset")
        self.horizontalLayout_4.addWidget(self.pushButton_dataset)
        self.pushButton_train = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_train.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color: rgb(255, 231, 151);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 18pt \"楷体\";\n"
"min-width:100px;    /*设置最小宽度*/\n"
"min-height:80px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_train.setObjectName("pushButton_train")
        self.horizontalLayout_4.addWidget(self.pushButton_train)
        self.pushButton_predict = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_predict.setMaximumSize(QtCore.QSize(131, 16777215))
        self.pushButton_predict.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color: rgb(255, 231, 151);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 18pt \"楷体\";\n"
"min-width:100px;    /*设置最小宽度*/\n"
"min-height:80px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_predict.setAutoDefault(False)
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.horizontalLayout_4.addWidget(self.pushButton_predict)
        self.label_version = QtWidgets.QLabel(self.centralwidget)
        self.label_version.setGeometry(QtCore.QRect(40, 20, 121, 20))
        self.label_version.setMinimumSize(QtCore.QSize(90, 0))
        self.label_version.setStyleSheet("QLabel{\n"
"\n"
"font: 16 px  \"Times New Roman\";\n"
"\n"
"}")
        self.label_version.setObjectName("label_version")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(950, 167, 141, 681))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(88, 34))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"\n"
"    color:white;    \n"
"    padding: 2px 4px;  \n"
"    background-color:#5F9EA0; \n"
"    font: 14pt \"楷体\";  /* 推荐使用无衬线字体更清晰  */\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"    font-weight: bold;\n"
"qproperty-alignment: \'AlignCenter\'; \n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton_AL1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_AL1.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color:rgb(168, 249, 124);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 16pt \"楷体\";\n"
"min-width:80px;    /*设置最小宽度*/\n"
"min-height:40px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_AL1.setObjectName("pushButton_AL1")
        self.verticalLayout.addWidget(self.pushButton_AL1)
        self.pushButton_AL2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_AL2.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color:rgb(168, 249, 124);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 16pt \"楷体\";\n"
"min-width:80px;    /*设置最小宽度*/\n"
"min-height:40px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_AL2.setObjectName("pushButton_AL2")
        self.verticalLayout.addWidget(self.pushButton_AL2)
        self.pushButton_AL5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_AL5.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color:rgb(168, 249, 124);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 16pt \"楷体\";\n"
"min-width:80px;    /*设置最小宽度*/\n"
"min-height:40px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_AL5.setObjectName("pushButton_AL5")
        self.verticalLayout.addWidget(self.pushButton_AL5)
        self.pushButton_AL4_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_AL4_2.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color:rgb(168, 249, 124);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 16pt \"楷体\";\n"
"min-width:80px;    /*设置最小宽度*/\n"
"min-height:40px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_AL4_2.setObjectName("pushButton_AL4_2")
        self.verticalLayout.addWidget(self.pushButton_AL4_2)
        self.pushButton_AL3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_AL3.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color:rgb(168, 249, 124);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 16pt \"楷体\";\n"
"min-width:80px;    /*设置最小宽度*/\n"
"min-height:40px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_AL3.setObjectName("pushButton_AL3")
        self.verticalLayout.addWidget(self.pushButton_AL3)
        self.pushButton_AL4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_AL4.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color:rgb(168, 249, 124);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 16pt \"楷体\";\n"
"min-width:80px;    /*设置最小宽度*/\n"
"min-height:40px;    /*设置最小高度*/\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(21, 151, 165); /* 悬停时背景色 */\n"
"    color: white;             /* 悬停时文字颜色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(38, 70, 83); /* 按下时背景色 */\n"
"}")
        self.pushButton_AL4.setObjectName("pushButton_AL4")
        self.verticalLayout.addWidget(self.pushButton_AL4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2b8cbe;           /* 科技蓝边框 */\n"
"    border-radius: 15px;\n"
"    padding: 2px 4px;\n"
"    background-color: #e0f3f8;           /* 浅蓝灰背景 */\n"
"    color: #0c2c84;                     /* 深蓝字体 */\n"
"    font:  14pt  \"楷体\" ;\n"
"    min-width: 80px;\n"
"font:bold;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7bccc4;          /* 悬浮时：蓝绿色 */\n"
"    border-color: #0868ac;              /* 加深边框 */\n"
"    color: #f7fcfd;                     /* 悬停文字改为白色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4eb3d3;          /* 按压时：科技蓝 */\n"
"    border-color: #084081;              /* 深蓝边框 */\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2b8cbe;           /* 科技蓝边框 */\n"
"    border-radius: 15px;\n"
"    padding: 2px 4px;\n"
"    background-color: #e0f3f8;           /* 浅蓝灰背景 */\n"
"    color: #0c2c84;                     /* 深蓝字体 */\n"
"    font:  14pt  \"楷体\" ;\n"
"    min-width: 80px;\n"
"font:bold;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7bccc4;          /* 悬浮时：蓝绿色 */\n"
"    border-color: #0868ac;              /* 加深边框 */\n"
"    color: #f7fcfd;                     /* 悬停文字改为白色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4eb3d3;          /* 按压时：科技蓝 */\n"
"    border-color: #084081;              /* 深蓝边框 */\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2b8cbe;           /* 科技蓝边框 */\n"
"    border-radius: 15px;\n"
"    padding: 2px 4px;\n"
"    background-color: #e0f3f8;           /* 浅蓝灰背景 */\n"
"    color: #0c2c84;                     /* 深蓝字体 */\n"
"    font: bold 14pt ;\n"
"    min-width: 80px;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7bccc4;          /* 悬浮时：蓝绿色 */\n"
"    border-color: #0868ac;              /* 加深边框 */\n"
"    color: #f7fcfd;                     /* 悬停文字改为白色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4eb3d3;          /* 按压时：科技蓝 */\n"
"    border-color: #084081;              /* 深蓝边框 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2b8cbe;           /* 科技蓝边框 */\n"
"    border-radius: 15px;\n"
"    padding: 2px 4px;\n"
"    background-color: #e0f3f8;           /* 浅蓝灰背景 */\n"
"    color: #0c2c84;                     /* 深蓝字体 */\n"
"    font: bold 14pt;\n"
"    min-width: 80px;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7bccc4;          /* 悬浮时：蓝绿色 */\n"
"    border-color: #0868ac;              /* 加深边框 */\n"
"    color: #f7fcfd;                     /* 悬停文字改为白色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4eb3d3;          /* 按压时：科技蓝 */\n"
"    border-color: #084081;              /* 深蓝边框 */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 1px solid #2b8cbe;           /* 科技蓝边框 */\n"
"    border-radius: 15px;\n"
"    padding: 2px 4px;\n"
"    background-color: #e0f3f8;           /* 浅蓝灰背景 */\n"
"    color: #0c2c84;                     /* 深蓝字体 */\n"
"    font: bold 12pt;\n"
"    min-width: 80px;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7bccc4;          /* 悬浮时：蓝绿色 */\n"
"    border-color: #0868ac;              /* 加深边框 */\n"
"    color: #f7fcfd;                     /* 悬停文字改为白色 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4eb3d3;          /* 按压时：科技蓝 */\n"
"    border-color: #084081;              /* 深蓝边框 */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_begin_to_predict = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_begin_to_predict.setStyleSheet("QPushButton{\n"
"    border:1px solid #64748B;   /* 浅灰蓝色边框，低调不突兀 */\n"
"    border-radius:15px;          /* 保持原有圆角设计 */\n"
"    padding:2px 4px;             /* 保持内边距 */\n"
"    background-color:#EFF6FF;    /* 淡蓝灰色背景，柔和不刺眼 */\n"
"    color:#1E293B;               /* 深灰蓝色文字，清晰易读 */\n"
"    font: 16pt \"楷体\";           /* 保持原有字体 */\n"
"    min-width:80px;              /* 保持最小宽度 */\n"
"    min-height:40px;             /* 保持最小高度 */\n"
"    font:bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #93C5FD;   /* 悬停时浅天蓝色，温和反馈 */\n"
"    color: #FFFFFF;              /* 悬停时白色文字，提升对比度 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3B82F6;   /* 按下时标准蓝色，明确反馈（科研常用主色调） */\n"
"}")
        self.pushButton_begin_to_predict.setObjectName("pushButton_begin_to_predict")
        self.verticalLayout.addWidget(self.pushButton_begin_to_predict)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(1099, 167, 251, 581))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt \"华文楷体\";\n"
"\n"
"font:bold 16px;        /*设置按钮文字和大小*/\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.listWidget_inputfeature = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidget_inputfeature.setAcceptDrops(True)
        self.listWidget_inputfeature.setDragEnabled(True)
        self.listWidget_inputfeature.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_inputfeature.setObjectName("listWidget_inputfeature")
        self.verticalLayout_2.addWidget(self.listWidget_inputfeature)
        self.pushButton_inputall = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_inputall.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_inputall.setFont(font)
        self.pushButton_inputall.setObjectName("pushButton_inputall")
        self.verticalLayout_2.addWidget(self.pushButton_inputall)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setStyleSheet("QLabel{\n"
"\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt \"华文楷体\";\n"
"\n"
"font: bold 16px;        /*设置按钮文字和大小*/\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.listWidget_outputfeature = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidget_outputfeature.setAcceptDrops(True)
        self.listWidget_outputfeature.setDragEnabled(True)
        self.listWidget_outputfeature.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_outputfeature.setObjectName("listWidget_outputfeature")
        self.verticalLayout_3.addWidget(self.listWidget_outputfeature)
        self.pushButton_outputall = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_outputall.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_outputall.setFont(font)
        self.pushButton_outputall.setObjectName("pushButton_outputall")
        self.verticalLayout_3.addWidget(self.pushButton_outputall)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(959, 80, 391, 72))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_testdata = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_testdata.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_testdata.setObjectName("verticalLayout_testdata")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_train_feature = QtWidgets.QLabel(self.layoutWidget3)
        self.label_train_feature.setMinimumSize(QtCore.QSize(0, 30))
        self.label_train_feature.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt \"华文楷体\";\n"
"\n"
"font:bold 16px;        /*设置按钮文字和大小*/\n"
"}")
        self.label_train_feature.setObjectName("label_train_feature")
        self.horizontalLayout_5.addWidget(self.label_train_feature)
        self.spinBox_train_start = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_train_start.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_train_start.setFont(font)
        self.spinBox_train_start.setStyleSheet("")
        self.spinBox_train_start.setMaximum(10000)
        self.spinBox_train_start.setObjectName("spinBox_train_start")
        self.horizontalLayout_5.addWidget(self.spinBox_train_start)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_5.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt \"华文楷体\";\n"
"\n"
"font:bold 16px;        /*设置按钮文字和大小*/\n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.spinBox_train_end = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_train_end.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_train_end.setFont(font)
        self.spinBox_train_end.setStyleSheet("")
        self.spinBox_train_end.setMaximum(999999)
        self.spinBox_train_end.setProperty("value", 9000)
        self.spinBox_train_end.setObjectName("spinBox_train_end")
        self.horizontalLayout_5.addWidget(self.spinBox_train_end)
        self.verticalLayout_testdata.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_test_feature = QtWidgets.QLabel(self.layoutWidget3)
        self.label_test_feature.setMinimumSize(QtCore.QSize(0, 30))
        self.label_test_feature.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt \"华文楷体\";\n"
"\n"
"font:bold 16px;        /*设置按钮文字和大小*/\n"
"}")
        self.label_test_feature.setObjectName("label_test_feature")
        self.horizontalLayout_6.addWidget(self.label_test_feature)
        self.spinBox_test_start = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_test_start.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.spinBox_test_start.setFont(font)
        self.spinBox_test_start.setMaximum(999999)
        self.spinBox_test_start.setObjectName("spinBox_test_start")
        self.horizontalLayout_6.addWidget(self.spinBox_test_start)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_6.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt \"华文楷体\";\n"
"\n"
"font:bold 16px;        /*设置按钮文字和大小*/\n"
"}")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.spinBox_test_end = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_test_end.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_test_end.setFont(font)
        self.spinBox_test_end.setStyleSheet("")
        self.spinBox_test_end.setMaximum(999999)
        self.spinBox_test_end.setProperty("value", 10000)
        self.spinBox_test_end.setObjectName("spinBox_test_end")
        self.horizontalLayout_6.addWidget(self.spinBox_test_end)
        self.verticalLayout_testdata.addLayout(self.horizontalLayout_6)
        self.checkBox_percentage = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_percentage.setGeometry(QtCore.QRect(1129, 50, 106, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_percentage.setFont(font)
        self.checkBox_percentage.setStyleSheet("QCheckBox {\n"
"\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"")
        self.checkBox_percentage.setObjectName("checkBox_percentage")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(81, 67, 100, 40))
        self.label.setMinimumSize(QtCore.QSize(50, 30))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"\n"
"\n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 16pt \"楷体\";\n"
"\n"
"font:bold;        /*设置按钮文字和大小*/\n"
"}")
        self.label.setObjectName("label")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(189, 67, 751, 42))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_dataset_file = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_dataset_file.setMinimumSize(QtCore.QSize(400, 40))
        self.lineEdit_dataset_file.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_dataset_file.setFont(font)
        self.lineEdit_dataset_file.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"color:red;\n"
"\n"
"}")
        self.lineEdit_dataset_file.setReadOnly(True)
        self.lineEdit_dataset_file.setObjectName("lineEdit_dataset_file")
        self.horizontalLayout_2.addWidget(self.lineEdit_dataset_file)
        self.lineEdit_dataset_nums = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_dataset_nums.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_dataset_nums.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_dataset_nums.setFont(font)
        self.lineEdit_dataset_nums.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"\n"
"}")
        self.lineEdit_dataset_nums.setObjectName("lineEdit_dataset_nums")
        self.horizontalLayout_2.addWidget(self.lineEdit_dataset_nums)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 536, 54, 12))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(960, 40, 155, 35))
        self.label_10.setMinimumSize(QtCore.QSize(88, 34))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_10.setStyleSheet("QLabel {\n"
"\n"
"    color:white;    \n"
"    padding: 2px 4px;  \n"
"    background-color:#5F9EA0; \n"
"    font: 14pt \"楷体\";  /* 推荐使用无衬线字体更清晰  */\n"
"    min-width: 80px;\n"
"    min-height: 30px;\n"
"    font-weight: bold;\n"
"qproperty-alignment: \'AlignCenter\'; \n"
"}")
        self.label_10.setObjectName("label_10")
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(63, 730, 871, 32))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_AL = QtWidgets.QLabel(self.layoutWidget5)
        self.label_AL.setMinimumSize(QtCore.QSize(60, 30))
        self.label_AL.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_AL.setFont(font)
        self.label_AL.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    \n"
"\n"
"\n"
"}")
        self.label_AL.setObjectName("label_AL")
        self.horizontalLayout.addWidget(self.label_AL)
        self.lineEdit_Algorithm_name = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_Algorithm_name.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Algorithm_name.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Algorithm_name.setFont(font)
        self.lineEdit_Algorithm_name.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"color:red;\n"
"\n"
"\n"
"}")
        self.lineEdit_Algorithm_name.setObjectName("lineEdit_Algorithm_name")
        self.horizontalLayout.addWidget(self.lineEdit_Algorithm_name)
        self.label_state = QtWidgets.QLabel(self.layoutWidget5)
        self.label_state.setMinimumSize(QtCore.QSize(60, 30))
        self.label_state.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_state.setFont(font)
        self.label_state.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    \n"
"\n"
"\n"
"}")
        self.label_state.setObjectName("label_state")
        self.horizontalLayout.addWidget(self.label_state)
        self.lineEdit_state = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_state.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_state.setFont(font)
        self.lineEdit_state.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"\n"
"}")
        self.lineEdit_state.setObjectName("lineEdit_state")
        self.horizontalLayout.addWidget(self.lineEdit_state)
        self.label_DEVICE = QtWidgets.QLabel(self.layoutWidget5)
        self.label_DEVICE.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_DEVICE.setFont(font)
        self.label_DEVICE.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt \"Times New Roman\";\n"
"font:bold;\n"
"\n"
"}")
        self.label_DEVICE.setObjectName("label_DEVICE")
        self.horizontalLayout.addWidget(self.label_DEVICE)
        self.lineEdit_DEVICE = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_DEVICE.setMinimumSize(QtCore.QSize(120, 30))
        self.lineEdit_DEVICE.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_DEVICE.setFont(font)
        self.lineEdit_DEVICE.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"\n"
"}")
        self.lineEdit_DEVICE.setReadOnly(True)
        self.lineEdit_DEVICE.setObjectName("lineEdit_DEVICE")
        self.horizontalLayout.addWidget(self.lineEdit_DEVICE)
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(63, 771, 871, 32))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_MSE = QtWidgets.QLabel(self.layoutWidget6)
        self.label_MSE.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_MSE.setFont(font)
        self.label_MSE.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    \n"
"\n"
"\n"
"}")
        self.label_MSE.setObjectName("label_MSE")
        self.horizontalLayout_7.addWidget(self.label_MSE)
        self.lineEdit_MSE = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_MSE.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_MSE.setFont(font)
        self.lineEdit_MSE.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"\n"
"}")
        self.lineEdit_MSE.setReadOnly(True)
        self.lineEdit_MSE.setObjectName("lineEdit_MSE")
        self.horizontalLayout_7.addWidget(self.lineEdit_MSE)
        self.label_RMSE = QtWidgets.QLabel(self.layoutWidget6)
        self.label_RMSE.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_RMSE.setFont(font)
        self.label_RMSE.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    \n"
"\n"
"\n"
"}")
        self.label_RMSE.setObjectName("label_RMSE")
        self.horizontalLayout_7.addWidget(self.label_RMSE)
        self.lineEdit_RMSE = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_RMSE.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_RMSE.setFont(font)
        self.lineEdit_RMSE.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"\n"
"}")
        self.lineEdit_RMSE.setReadOnly(True)
        self.lineEdit_RMSE.setObjectName("lineEdit_RMSE")
        self.horizontalLayout_7.addWidget(self.lineEdit_RMSE)
        self.label_MAE = QtWidgets.QLabel(self.layoutWidget6)
        self.label_MAE.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_MAE.setFont(font)
        self.label_MAE.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    \n"
"\n"
"\n"
"}")
        self.label_MAE.setObjectName("label_MAE")
        self.horizontalLayout_7.addWidget(self.label_MAE)
        self.lineEdit_MAE = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_MAE.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_MAE.setFont(font)
        self.lineEdit_MAE.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"\n"
"}")
        self.lineEdit_MAE.setReadOnly(True)
        self.lineEdit_MAE.setObjectName("lineEdit_MAE")
        self.horizontalLayout_7.addWidget(self.lineEdit_MAE)
        self.layoutWidget7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(890, 390, 42, 70))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_top = QtWidgets.QPushButton(self.layoutWidget7)
        self.pushButton_top.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_top.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_top.setFont(font)
        self.pushButton_top.setObjectName("pushButton_top")
        self.verticalLayout_4.addWidget(self.pushButton_top)
        self.pushButton_bottom = QtWidgets.QPushButton(self.layoutWidget7)
        self.pushButton_bottom.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_bottom.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_bottom.setFont(font)
        self.pushButton_bottom.setObjectName("pushButton_bottom")
        self.verticalLayout_4.addWidget(self.pushButton_bottom)
        self.shuffle_yes_or_no = QtWidgets.QCheckBox(self.centralwidget)
        self.shuffle_yes_or_no.setGeometry(QtCore.QRect(1240, 50, 106, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.shuffle_yes_or_no.setFont(font)
        self.shuffle_yes_or_no.setStyleSheet("QCheckBox {\n"
"\n"
"    spacing: 5px;\n"
"}\n"
"\n"
"")
        self.shuffle_yes_or_no.setObjectName("shuffle_yes_or_no")
        self.pushButton_help = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_help.setGeometry(QtCore.QRect(1290, 10, 75, 23))
        self.pushButton_help.setObjectName("pushButton_help")
        self.layoutWidget8 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget8.setGeometry(QtCore.QRect(1130, 750, 201, 101))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_save_pretrained_model = QtWidgets.QPushButton(self.layoutWidget8)
        self.pushButton_save_pretrained_model.setMinimumSize(QtCore.QSize(87, 44))
        self.pushButton_save_pretrained_model.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButton_save_pretrained_model.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(60, 75, 90);       /* 深灰蓝边框，类似实验仪器金属色 */\n"
"    border-radius: 8px;                      /* 适中圆角更显严谨 */\n"
"    background-color: rgb(240, 245, 250);    /* 极浅灰蓝背景，参考实验室白板 */\n"
"    color: rgb(30, 50, 70);                 /* 深灰蓝文字，如学术文献印刷色 */\n"
"    font: bold 14pt \"微软雅黑\";\n"
"    min-width: 85px;\n"
"    min-height: 42px;\n"
" \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 230, 240);    /* 悬停时轻微加深背景 */\n"
"    border-color: rgb(40, 60, 80);          /* 加深边框模拟金属反光 */\n"
"    color: rgb(20, 40, 60);                 /* 文字颜色同步加深 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(60, 75, 90);      /* 按压状态与边框同色 */\n"
"    color: rgb(230, 235, 240);              /* 浅灰白文字确保可读性 */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(250, 250, 250);    /* 禁用状态极浅灰 */\n"
"    color: rgb(180, 190, 200);              /* 灰蓝文字表示不可用 */\n"
"    border-color: rgb(210, 220, 230);\n"
"}")
        self.pushButton_save_pretrained_model.setObjectName("pushButton_save_pretrained_model")
        self.verticalLayout_5.addWidget(self.pushButton_save_pretrained_model)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget8)
        self.pushButton_8.setMinimumSize(QtCore.QSize(87, 44))
        self.pushButton_8.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(60, 75, 90);       /* 深灰蓝边框，类似实验仪器金属色 */\n"
"    border-radius: 8px;                      /* 适中圆角更显严谨 */\n"
"    background-color: rgb(240, 245, 250);    /* 极浅灰蓝背景，参考实验室白板 */\n"
"    color: rgb(30, 50, 70);                 /* 深灰蓝文字，如学术文献印刷色 */\n"
"    font: bold 14pt \"微软雅黑\";\n"
"    min-width: 85px;\n"
"    min-height: 42px;\n"
" \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 230, 240);    /* 悬停时轻微加深背景 */\n"
"    border-color: rgb(40, 60, 80);          /* 加深边框模拟金属反光 */\n"
"    color: rgb(20, 40, 60);                 /* 文字颜色同步加深 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(60, 75, 90);      /* 按压状态与边框同色 */\n"
"    color: rgb(230, 235, 240);              /* 浅灰白文字确保可读性 */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(250, 250, 250);    /* 禁用状态极浅灰 */\n"
"    color: rgb(180, 190, 200);              /* 灰蓝文字表示不可用 */\n"
"    border-color: rgb(210, 220, 230);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_5.addWidget(self.pushButton_8)
        self.layoutWidget9 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget9.setGeometry(QtCore.QRect(64, 810, 581, 34))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_R2 = QtWidgets.QLabel(self.layoutWidget9)
        self.label_R2.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_R2.setFont(font)
        self.label_R2.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt  \"Times New Roman\";\n"
"font:bold;\n"
"\n"
"\n"
"}")
        self.label_R2.setObjectName("label_R2")
        self.horizontalLayout_9.addWidget(self.label_R2)
        self.lineEdit_R2 = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_R2.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_R2.setFont(font)
        self.lineEdit_R2.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"\n"
"}")
        self.lineEdit_R2.setReadOnly(True)
        self.lineEdit_R2.setObjectName("lineEdit_R2")
        self.horizontalLayout_9.addWidget(self.lineEdit_R2)
        self.label_R2_db_within_3_ratio = QtWidgets.QLabel(self.layoutWidget9)
        self.label_R2_db_within_3_ratio.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_R2_db_within_3_ratio.setFont(font)
        self.label_R2_db_within_3_ratio.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt  \"楷体\";\n"
"font:bold;\n"
"\n"
"\n"
"}")
        self.label_R2_db_within_3_ratio.setObjectName("label_R2_db_within_3_ratio")
        self.horizontalLayout_9.addWidget(self.label_R2_db_within_3_ratio)
        self.lineEdit_db_within_3_ratio = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEdit_db_within_3_ratio.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_db_within_3_ratio.setFont(font)
        self.lineEdit_db_within_3_ratio.setStyleSheet("QLineEdit{\n"
"\n"
"border:1px solid black; \n"
"border-radius:10px; \n"
"\n"
"}")
        self.lineEdit_db_within_3_ratio.setReadOnly(True)
        self.lineEdit_db_within_3_ratio.setObjectName("lineEdit_db_within_3_ratio")
        self.horizontalLayout_9.addWidget(self.lineEdit_db_within_3_ratio)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.layoutWidget10 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget10.setGeometry(QtCore.QRect(660, 810, 250, 32))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_AL_2 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_AL_2.setMinimumSize(QtCore.QSize(60, 30))
        self.label_AL_2.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_AL_2.setFont(font)
        self.label_AL_2.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    \n"
"\n"
"\n"
"}")
        self.label_AL_2.setObjectName("label_AL_2")
        self.horizontalLayout_8.addWidget(self.label_AL_2)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget10)
        self.progressBar.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_8.addWidget(self.progressBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.pushButton_AL1.clicked.connect(MainWindow.AL_DT_para) # type: ignore
        self.pushButton_AL2.clicked.connect(MainWindow.AL_RF_para) # type: ignore
        self.pushButton_AL3.clicked.connect(MainWindow.AL_SVM_para) # type: ignore
        self.pushButton_AL4.clicked.connect(MainWindow.AL_MLP_para) # type: ignore
        self.pushButton_AL5.clicked.connect(MainWindow.AL_ET_para) # type: ignore
        self.pushButton.clicked.connect(MainWindow.AL_GL_para) # type: ignore
        self.checkBox_percentage.clicked.connect(MainWindow.change_percentage) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow.AL_MTW_para) # type: ignore
        self.pushButton_3.clicked.connect(MainWindow.AL_REMTW_para) # type: ignore
        self.pushButton_vibration_analysis.clicked.connect(MainWindow.AL_VA_para) # type: ignore
        self.pushButton_8.clicked.connect(MainWindow.save) # type: ignore
        self.pushButton_predict.clicked.connect(MainWindow.AL_load_model_para) # type: ignore
        self.pushButton_4.clicked.connect(MainWindow.AL_MMoE_para) # type: ignore
        self.pushButton_inputall.clicked.connect(MainWindow.change_CheckBox_input) # type: ignore
        self.pushButton_outputall.clicked.connect(MainWindow.change_CheckBox_output) # type: ignore
        self.pushButton_train.clicked.connect(MainWindow.openfolder) # type: ignore
        self.pushButton_5.clicked.connect(MainWindow.AL_GP_para) # type: ignore
        self.pushButton_otherpara.clicked.connect(MainWindow.AL_Other_para) # type: ignore
        self.shuffle_yes_or_no.clicked.connect(self.checkBox_percentage.toggle) # type: ignore
        self.shuffle_yes_or_no.clicked.connect(MainWindow.change_percentage) # type: ignore
        self.pushButton_AL4_2.clicked.connect(MainWindow.AL_LR_para) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "多目标回归预示分析系统"))
        self.label_headline.setText(_translate("MainWindow", "多目标回归预示分析系统"))
        self.pushButton_vibration_analysis.setToolTip(_translate("MainWindow", "<html><head/><body><p>设置采样频率并导入振动数据，可以是多组或者是单组</p></body></html>"))
        self.pushButton_vibration_analysis.setText(_translate("MainWindow", "振动分析"))
        self.pushButton_otherpara.setText(_translate("MainWindow", "输入参数"))
        self.pushButton_dataset.setText(_translate("MainWindow", "数据集合成"))
        self.pushButton_train.setText(_translate("MainWindow", "训练验模"))
        self.pushButton_predict.setToolTip(_translate("MainWindow", "<html><head/><body><p>点击预测按钮，可进行导入预训练模型的设置，导入预测数据，确认后可点击右下方开始预测按钮进行预测</p></body></html>"))
        self.pushButton_predict.setText(_translate("MainWindow", "预测"))
        self.label_version.setText(_translate("MainWindow", "v4.0 2025.11.28"))
        self.label_2.setText(_translate("MainWindow", "算法模型"))
        self.pushButton_AL1.setToolTip(_translate("MainWindow", "<html><head/><body><p>决策树算法</p></body></html>"))
        self.pushButton_AL1.setText(_translate("MainWindow", "决策树"))
        self.pushButton_AL2.setToolTip(_translate("MainWindow", "<html><head/><body><p>随机森林算法</p></body></html>"))
        self.pushButton_AL2.setText(_translate("MainWindow", "随机森林"))
        self.pushButton_AL5.setToolTip(_translate("MainWindow", "<html><head/><body><p>极端树算法</p></body></html>"))
        self.pushButton_AL5.setText(_translate("MainWindow", "极端树"))
        self.pushButton_AL4_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>多层感知机算法</p></body></html>"))
        self.pushButton_AL4_2.setText(_translate("MainWindow", "线性回归"))
        self.pushButton_AL3.setToolTip(_translate("MainWindow", "<html><head/><body><p>支持向量机算法</p></body></html>"))
        self.pushButton_AL3.setText(_translate("MainWindow", "支持向量机"))
        self.pushButton_AL4.setToolTip(_translate("MainWindow", "<html><head/><body><p>多层感知机算法</p></body></html>"))
        self.pushButton_AL4.setText(_translate("MainWindow", "多层感知机"))
        self.pushButton_5.setText(_translate("MainWindow", "高斯过程"))
        self.pushButton_4.setText(_translate("MainWindow", "多门控\n"
"混合专家"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:400;\">GroupLasso：基于 L1/L2混合范数正则化的多任务学习模型</span></p><p><span style=\" font-size:12pt; font-weight:400;\">图表通俗解读-总系数热力图：</span><span style=\" font-family:\'Inter,-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:12pt; font-weight:400; color:rgba(0,0,0,0.847059); background-color:#ffffff;\">像 “关系地图”，行是输入特征、列是输出任务，颜色越深代表该特征对对应任务的影响越强，快速定位 “哪个特征对哪个任务最关键”；</span></p><p><span style=\" font-family:\'Inter,-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:12pt; font-weight:400; color:rgba(0,0,0,0.847059); background-color:#ffffff;\">共享系数热力图则聚焦 “通用特征”，若某特征行的所有任务列颜色均深，说明其是所有任务的共同核心，抓好它能同步提升多个任务效果。</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "GroupLasso"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:400;\">Multitask Wasserstein：基于Wasserstein距离正则化的稀疏多任务回归模型</span></p><p><span style=\" font-family:\'Inter,-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:10pt; font-weight:400; color:rgba(0,0,0,0.847059); background-color:#ffffff;\">MTW 算法的图表更细致，能分清影响的 “好坏” 与 “全局优先级”。</span></p><p><span style=\" font-family:\'Inter,-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:10pt; font-weight:400; color:rgba(0,0,0,0.847059); background-color:#ffffff;\">系数热力图不仅看颜色深浅（影响强度），还通过双色区分正负影响 —— 比如红色代表促进、蓝色代表抑制，直观展现特征的 “两面性”；</span></p><p><span style=\" font-family:\'Inter,-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:10pt; font-weight:400; color:rgba(0,0,0,0.847059); background-color:#ffffff;\">Wasserstein 重心柱状图是 “特征排名榜”，柱子越高，特征在所有任务中的整体重要性越强，帮你快速锁定全局核心。</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "Multitask \n"
"Wasserstein"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:400;\">Reweighted Multitask Wasserstein：基于Wasserstein距离正则化和L0.5稀疏约束的多任务回归模型</span></p><p><span style=\" font-family:\'Inter,-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:10pt; font-weight:400; color:rgba(0,0,0,0.847059); background-color:#ffffff;\">REMTW 是 MTW 的 “精准版”，核心是过滤无用信息。</span></p><p><span style=\" font-family:\'Inter,-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:10pt; font-weight:400; color:rgba(0,0,0,0.847059); background-color:#ffffff;\">系数热力图的特点是 “稀疏性更强”，无关特征颜色几乎透明，仅核心关联区域颜色突出，避免被噪音特征误导；</span></p><p><span style=\" font-family:\'Inter,-apple-system,BlinkMacSystemFont,Segoe UI,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Helvetica Neue,Helvetica,Arial,sans-serif\'; font-size:10pt; font-weight:400; color:rgba(0,0,0,0.847059); background-color:#ffffff;\">重心柱状图的分化更明显，核心特征的柱子显著高于其他，让 “真重要” 特征一目了然，减少决策干扰。</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "Reweighted\n"
"Multitask\n"
"Wasserstein"))
        self.pushButton_begin_to_predict.setToolTip(_translate("MainWindow", "<html><head/><body><p>这是加载预训练模型后可点击的开始预测按钮</p></body></html>"))
        self.pushButton_begin_to_predict.setText(_translate("MainWindow", "开始预测"))
        self.label_3.setText(_translate("MainWindow", "输入特征"))
        self.pushButton_inputall.setText(_translate("MainWindow", "全选"))
        self.label_4.setText(_translate("MainWindow", "输出特征"))
        self.pushButton_outputall.setText(_translate("MainWindow", "全选"))
        self.label_train_feature.setText(_translate("MainWindow", "训练样本数:"))
        self.label_5.setText(_translate("MainWindow", ":"))
        self.label_test_feature.setText(_translate("MainWindow", "测试样本数:"))
        self.label_6.setText(_translate("MainWindow", ":"))
        self.checkBox_percentage.setText(_translate("MainWindow", "百分比显示"))
        self.label.setText(_translate("MainWindow", "数据集:"))
        self.lineEdit_dataset_file.setText(_translate("MainWindow", "请点击下方训练验模按钮导入训练数据！"))
        self.label_10.setText(_translate("MainWindow", "实验数据调控区"))
        self.label_AL.setToolTip(_translate("MainWindow", "<html><head/><body><p>当前使用的算法</p></body></html>"))
        self.label_AL.setText(_translate("MainWindow", "算法:"))
        self.lineEdit_Algorithm_name.setText(_translate("MainWindow", "请在右侧区域选择所需算法模型！"))
        self.label_state.setToolTip(_translate("MainWindow", "<html><head/><body><p>当前训练状态</p></body></html>"))
        self.label_state.setText(_translate("MainWindow", "状态:"))
        self.label_DEVICE.setToolTip(_translate("MainWindow", "<html><head/><body><p>当前使用的设备</p></body></html>"))
        self.label_DEVICE.setText(_translate("MainWindow", "DEVICE"))
        self.label_MSE.setToolTip(_translate("MainWindow", "<html><head/><body><p><a href=\"https://so.csdn.net/so/search?q=%E5%9D%87%E6%96%B9%E8%AF%AF%E5%B7%AE&amp;spm=1001.2101.3001.7020\"><span style=\" font-family:\'-apple-system,SF UI Text,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif\'; font-size:16px; color:#000000;\">均方误差，</span></a><span style=\" font-family:\'-apple-system,SF UI Text,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif\'; font-size:16px; font-weight:400; color:#000000; background-color:#ffffff;\">常用于评估模型的预测值与真实值之间的差异。它通过计算预测值和真实值之间的误差平方的平均值，来衡量模型的预测性能。</span><a href=\"https://so.csdn.net/so/search?q=%E5%9D%87%E6%96%B9%E8%AF%AF%E5%B7%AE&amp;spm=1001.2101.3001.7020\"><span style=\" font-family:\'-apple-system,SF UI Text,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif\'; font-size:16px; font-weight:400; color:#000000;\">均方误差</span></a><span style=\" font-family:\'-apple-system,SF UI Text,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif\'; font-size:16px; font-weight:400; color:#000000; background-color:#ffffff;\">越小，表示模型的预测越准确；均方误差越大，表示模型的预测误差越大。</span></p></body></html>"))
        self.label_MSE.setText(_translate("MainWindow", "MSE"))
        self.label_RMSE.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'-apple-system,SF UI Text,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif\'; font-size:16px; font-weight:400; color:#4d4d4d; background-color:#ffffff;\">均方根误差，它表示预测值和观测值之间差异（称为残差）的样本标准差。均方根误差为了说明样本的离散程度。做非</span><span style=\" font-family:\'-apple-system,SF UI Text,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif\'; font-size:16px; font-weight:400; color:#4ea1db;\">线性</span><span style=\" font-family:\'-apple-system,SF UI Text,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif\'; font-size:16px; font-weight:400; color:#4d4d4d; background-color:#ffffff;\">拟合时,RMSE越小越好。</span></p></body></html>"))
        self.label_RMSE.setText(_translate("MainWindow", "RMSE"))
        self.label_MAE.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'-apple-system,SF UI Text,Arial,PingFang SC,Hiragino Sans GB,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif\'; font-size:16px; font-weight:400; color:#4d4d4d; background-color:#ffffff;\">平均绝对值误差，它表示预测值和观测值之间绝对误差的平均值</span></p></body></html>"))
        self.label_MAE.setText(_translate("MainWindow", "MAE"))
        self.pushButton_top.setToolTip(_translate("MainWindow", "<html><head/><body><p>上翻页</p></body></html>"))
        self.pushButton_top.setText(_translate("MainWindow", "↑"))
        self.pushButton_bottom.setToolTip(_translate("MainWindow", "<html><head/><body><p>下翻页</p></body></html>"))
        self.pushButton_bottom.setText(_translate("MainWindow", "↓"))
        self.shuffle_yes_or_no.setText(_translate("MainWindow", "shuffle"))
        self.pushButton_help.setText(_translate("MainWindow", "帮助文档"))
        self.pushButton_save_pretrained_model.setText(_translate("MainWindow", "保存训练模型"))
        self.pushButton_8.setText(_translate("MainWindow", "保存预测结果"))
        self.label_R2.setToolTip(_translate("MainWindow", "<html><head/><body><p>决定系数R^2,越接近1，代表模型拟合能力越强</p></body></html>"))
        self.label_R2.setText(_translate("MainWindow", "R^2"))
        self.label_R2_db_within_3_ratio.setToolTip(_translate("MainWindow", "<html><head/><body><p>决定系数R^2,越接近1，代表模型拟合能力越强</p></body></html>"))
        self.label_R2_db_within_3_ratio.setText(_translate("MainWindow", "±3dB内比例"))
        self.label_AL_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>当前使用的算法</p></body></html>"))
        self.label_AL_2.setText(_translate("MainWindow", "训练进度"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
