# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zs\Desktop\新项目\ui\algorithms4_MLP_para.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MLP_para(object):
    def setupUi(self, MLP_para):
        MLP_para.setObjectName("MLP_para")
        MLP_para.resize(639, 431)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MLP_para.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MLP_para)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 270, 211, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color: rgb(149, 236, 165);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 18pt \"楷体\";\n"
"\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(177, 244, 155);    /* 悬停时背景色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(99, 181, 255);     /* 点击时背景色 */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color: rgb(149, 236, 165);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 18pt \"楷体\";\n"
"\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(177, 244, 155);    /* 悬停时背景色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(99, 181, 255);     /* 点击时背景色 */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 70, 362, 198))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_hidden_layer_sizes = QtWidgets.QLabel(self.layoutWidget1)
        self.label_hidden_layer_sizes.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.label_hidden_layer_sizes.setObjectName("label_hidden_layer_sizes")
        self.verticalLayout.addWidget(self.label_hidden_layer_sizes)
        self.label_max_iter = QtWidgets.QLabel(self.layoutWidget1)
        self.label_max_iter.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.label_max_iter.setObjectName("label_max_iter")
        self.verticalLayout.addWidget(self.label_max_iter)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_random_state = QtWidgets.QLabel(self.layoutWidget1)
        self.label_random_state.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.label_random_state.setObjectName("label_random_state")
        self.verticalLayout.addWidget(self.label_random_state)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_hidden_layer_sizes = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_hidden_layer_sizes.setMinimumSize(QtCore.QSize(80, 30))
        self.lineEdit_hidden_layer_sizes.setObjectName("lineEdit_hidden_layer_sizes")
        self.verticalLayout_2.addWidget(self.lineEdit_hidden_layer_sizes)
        self.spinBox_max_iter = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_max_iter.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox_max_iter.setFont(font)
        self.spinBox_max_iter.setStyleSheet("QSpinBox::up-button:pressed {\n"
"    margin-top: 4px;  /* 模拟按压下沉 */\n"
"}\n"
"QSpinBox::down-button:pressed {\n"
"    margin-top: 4px;\n"
"}")
        self.spinBox_max_iter.setMaximum(10000)
        self.spinBox_max_iter.setProperty("value", 500)
        self.spinBox_max_iter.setObjectName("spinBox_max_iter")
        self.verticalLayout_2.addWidget(self.spinBox_max_iter)
        self.doubleSpinBox_mlp_alpha = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.doubleSpinBox_mlp_alpha.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_mlp_alpha.setFont(font)
        self.doubleSpinBox_mlp_alpha.setStyleSheet("QDoubleSpinBox::up-button:pressed {\n"
"    margin-top: 4px;  /* 模拟按压下沉 */\n"
"}\n"
"QDoubleSpinBox::down-button:pressed {\n"
"    margin-top: 4px;\n"
"}")
        self.doubleSpinBox_mlp_alpha.setDecimals(4)
        self.doubleSpinBox_mlp_alpha.setProperty("value", 0.0001)
        self.doubleSpinBox_mlp_alpha.setObjectName("doubleSpinBox_mlp_alpha")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_mlp_alpha)
        self.spinBox_random_state = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_random_state.setMinimumSize(QtCore.QSize(80, 30))
        self.spinBox_random_state.setStyleSheet("QSpinBox::up-button:pressed {\n"
"    margin-top: 4px;  /* 模拟按压下沉 */\n"
"}\n"
"QSpinBox::down-button:pressed {\n"
"    margin-top: 4px;\n"
"}")
        self.spinBox_random_state.setProperty("value", 42)
        self.spinBox_random_state.setObjectName("spinBox_random_state")
        self.verticalLayout_2.addWidget(self.spinBox_random_state)
        self.comboBox_scale_features = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_scale_features.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_scale_features.setObjectName("comboBox_scale_features")
        self.comboBox_scale_features.addItem("")
        self.comboBox_scale_features.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_scale_features)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MLP_para.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MLP_para)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 23))
        self.menubar.setObjectName("menubar")
        MLP_para.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MLP_para)
        self.statusbar.setObjectName("statusbar")
        MLP_para.setStatusBar(self.statusbar)

        self.retranslateUi(MLP_para)
        self.pushButton.clicked.connect(MLP_para.Confirm) # type: ignore
        self.pushButton_2.clicked.connect(MLP_para.close) # type: ignore
        self.pushButton.released.connect(MLP_para.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MLP_para)

    def retranslateUi(self, MLP_para):
        _translate = QtCore.QCoreApplication.translate
        MLP_para.setWindowTitle(_translate("MLP_para", "MLP：参数设置"))
        self.pushButton.setText(_translate("MLP_para", "确认"))
        self.pushButton_2.setText(_translate("MLP_para", "取消"))
        self.label_hidden_layer_sizes.setText(_translate("MLP_para", "hidden_layer_sizes"))
        self.label_max_iter.setText(_translate("MLP_para", "max_iter"))
        self.label_2.setText(_translate("MLP_para", "mlp_alpha"))
        self.label_random_state.setText(_translate("MLP_para", "random_state"))
        self.label.setText(_translate("MLP_para", "scale_features"))
        self.lineEdit_hidden_layer_sizes.setText(_translate("MLP_para", "100,50"))
        self.comboBox_scale_features.setItemText(0, _translate("MLP_para", "False"))
        self.comboBox_scale_features.setItemText(1, _translate("MLP_para", "True"))
