# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zs\Desktop\beifen\新项目\ui\Load_model_para.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Load_model_para(object):
    def setupUi(self, Load_model_para):
        Load_model_para.setObjectName("Load_model_para")
        Load_model_para.resize(580, 300)
        self.centralwidget = QtWidgets.QWidget(Load_model_para)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 210, 161, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color: rgb(149, 236, 165);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 18pt \"楷体\";\n"
"\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(177, 244, 155);    /* 悬停时背景色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(99, 181, 255);     /* 点击时背景色 */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border:1px solid red;   /*边框的粗细，颜色*/\n"
"border-radius:15px;    /*设置圆角半径 */\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"background-color: rgb(149, 236, 165);    /*背景颜色*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 18pt \"楷体\";\n"
"\n"
"font:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(177, 244, 155);    /* 悬停时背景色 */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color:rgb(99, 181, 255);     /* 点击时背景色 */\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 50, 521, 132))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_pretrained_model_path = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_pretrained_model_path.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_pretrained_model_path.setFont(font)
        self.lineEdit_pretrained_model_path.setText("")
        self.lineEdit_pretrained_model_path.setReadOnly(True)
        self.lineEdit_pretrained_model_path.setObjectName("lineEdit_pretrained_model_path")
        self.horizontalLayout.addWidget(self.lineEdit_pretrained_model_path)
        self.pushButton_load_model = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_load_model.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_load_model.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_load_model.setFont(font)
        self.pushButton_load_model.setObjectName("pushButton_load_model")
        self.horizontalLayout.addWidget(self.pushButton_load_model)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_file_predict_data = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_file_predict_data.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lineEdit_file_predict_data.setFont(font)
        self.lineEdit_file_predict_data.setObjectName("lineEdit_file_predict_data")
        self.horizontalLayout_3.addWidget(self.lineEdit_file_predict_data)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_train_feature = QtWidgets.QLabel(self.layoutWidget1)
        self.label_train_feature.setMinimumSize(QtCore.QSize(0, 30))
        self.label_train_feature.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt \"华文楷体\";\n"
"\n"
"font:bold 16px;        /*设置按钮文字和大小*/\n"
"}")
        self.label_train_feature.setObjectName("label_train_feature")
        self.horizontalLayout_4.addWidget(self.label_train_feature)
        self.spinBox_predict_start = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_predict_start.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_predict_start.setFont(font)
        self.spinBox_predict_start.setStyleSheet("")
        self.spinBox_predict_start.setObjectName("spinBox_predict_start")
        self.horizontalLayout_4.addWidget(self.spinBox_predict_start)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_5.setStyleSheet("QLabel{\n"
"\n"
"   text-align: center;    \n"
" qproperty-alignment: \'AlignCenter\';   \n"
"\n"
"padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
"color:rgb(0, 0, 0);        /*字体颜色*/\n"
"    font: 12pt \"华文楷体\";\n"
"\n"
"font:bold 16px;        /*设置按钮文字和大小*/\n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.spinBox_predict_end = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_predict_end.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox_predict_end.setFont(font)
        self.spinBox_predict_end.setStyleSheet("")
        self.spinBox_predict_end.setMaximum(999999)
        self.spinBox_predict_end.setProperty("value", 1000)
        self.spinBox_predict_end.setObjectName("spinBox_predict_end")
        self.horizontalLayout_4.addWidget(self.spinBox_predict_end)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        Load_model_para.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Load_model_para)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 23))
        self.menubar.setObjectName("menubar")
        Load_model_para.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Load_model_para)
        self.statusbar.setObjectName("statusbar")
        Load_model_para.setStatusBar(self.statusbar)

        self.retranslateUi(Load_model_para)
        self.pushButton_2.clicked.connect(Load_model_para.Confirm) # type: ignore
        self.pushButton_3.clicked.connect(Load_model_para.close) # type: ignore
        self.pushButton_2.clicked.connect(Load_model_para.close) # type: ignore
        self.pushButton_load_model.clicked.connect(Load_model_para.load_pretrained_model) # type: ignore
        self.pushButton.clicked.connect(Load_model_para.load_predict_data) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Load_model_para)

    def retranslateUi(self, Load_model_para):
        _translate = QtCore.QCoreApplication.translate
        Load_model_para.setWindowTitle(_translate("Load_model_para", "加载预训练模型：参数设置"))
        self.pushButton_2.setText(_translate("Load_model_para", "确认"))
        self.pushButton_3.setText(_translate("Load_model_para", "取消"))
        self.label.setText(_translate("Load_model_para", "加载预训练模型"))
        self.pushButton_load_model.setText(_translate("Load_model_para", "..."))
        self.label_2.setText(_translate("Load_model_para", "导入预测数据    "))
        self.pushButton.setText(_translate("Load_model_para", "..."))
        self.label_train_feature.setText(_translate("Load_model_para", "预测样本数:"))
        self.label_5.setText(_translate("Load_model_para", ":"))
