# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\zs\Desktop\新项目\ui\Other.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Other(object):
    def setupUi(self, Other):
        Other.setObjectName("Other")
        Other.resize(665, 363)
        self.centralwidget = QtWidgets.QWidget(Other)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 70, 174, 116))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_para = QtWidgets.QPushButton(self.layoutWidget)
        self.load_para.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.load_para.setObjectName("load_para")
        self.verticalLayout.addWidget(self.load_para)
        self.data_ps = QtWidgets.QPushButton(self.layoutWidget)
        self.data_ps.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.data_ps.setObjectName("data_ps")
        self.verticalLayout.addWidget(self.data_ps)
        self.pushButton_save_data = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_save_data.setStyleSheet("QPushButton {\n"
"    border: 1px solid rgb(70, 130, 180);   /* 增强为科研蓝边框，参考Nature期刊图表色 */\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    background-color: rgb(255, 255, 255);  /* 纯白背景提升对比度 */\n"
"    color: rgb(30, 80, 120);               /* 深海军蓝文字，对比度达8:1 */\n"
"    font: bold 16pt \"Times New Roman\";     \n"
"    /* 强化阴影效果 */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: rgb(0, 100, 180);        /* 悬停时使用更高饱和的科研蓝 */\n"
"    background-color: rgb(240, 248, 255);  /* 极浅蓝悬停反馈 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(220, 240, 255);  /* 按压状态模拟墨水渗透效果 */\n"
"}")
        self.pushButton_save_data.setObjectName("pushButton_save_data")
        self.verticalLayout.addWidget(self.pushButton_save_data)
        Other.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Other)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 23))
        self.menubar.setObjectName("menubar")
        Other.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Other)
        self.statusbar.setObjectName("statusbar")
        Other.setStatusBar(self.statusbar)

        self.retranslateUi(Other)
        QtCore.QMetaObject.connectSlotsByName(Other)

    def retranslateUi(self, Other):
        _translate = QtCore.QCoreApplication.translate
        Other.setWindowTitle(_translate("Other", "其他参数模块"))
        self.load_para.setText(_translate("Other", "导入特征参数"))
        self.data_ps.setText(_translate("Other", "数据备注"))
        self.pushButton_save_data.setText(_translate("Other", "数据保存"))
